import type { ComponentType } from "react";
import {
  BaselineReportView,
  IndustryResearchReportView,
  MarketSnapshotView,
  MarketResearchView,
  DiagnosticReportView,
  DataCollectionPlanView,
  DecisionPackView,
  BestPracticesView,
  FailureAnalysisView,
  BusinessPlanView,
  MenuCardView,
  SupplierListView,
  MenuCostView,
  MenuPreiskalkulationView,
  RealEstateView,
  FinancialPlanningView,
  PersonnelPlanView,
  WorkProcessesView,
  StartupConsultingGuideView,
  MarketingStrategyView,
  SwotReportView,
} from "@/components/ArtifactReportView";

/** Map artifact.type → React report view (null = no dedicated view, use exportHtml). */
export const ARTIFACT_REPORT_VIEW_MAP: Record<
  string,
  ComponentType<{ content: Record<string, unknown> }> | null
> = {
  baseline: BaselineReportView,
  industry_research: IndustryResearchReportView,
  market: MarketSnapshotView,
  market_research: MarketResearchView,
  diagnostic: DiagnosticReportView,
  data_collection_plan: DataCollectionPlanView,
  decision_pack: DecisionPackView,
  best_practices: BestPracticesView,
  failure_analysis: FailureAnalysisView,
  business_plan: BusinessPlanView,
  menu_card: MenuCardView,
  supplier_list: SupplierListView,
  menu_cost: MenuCostView,
  menu_preiskalkulation: MenuPreiskalkulationView,
  real_estate: RealEstateView,
  financial_planning: FinancialPlanningView,
  personnel_plan: PersonnelPlanView,
  work_processes: WorkProcessesView,
  startup_guide: StartupConsultingGuideView,
  marketing_strategy: MarketingStrategyView,
  swot_analysis: SwotReportView,
  knowledge_digest: null,
  strategy_pack: null,
};
