/**
 * Planungsphasen und Planungsbereiche – Framework für Workflows
 * Workflows sind Phasen und Bereichen zugeordnet, mit optionalen Unterworkflows (Steps).
 */

import type { Locale } from "@/lib/i18n";

/** Workflows that consume each artifact/data type – für "Workflows neu starten" nach manueller Bearbeitung */
export const DATA_TO_WORKFLOWS: Record<string, string[]> = {
  company_profile: ["WF_BASELINE", "WF_MARKET", "WF_RESEARCH", "WF_VALUE_PROPOSITION", "WF_COMPETITOR_ANALYSIS", "WF_SWOT", "WF_TREND_ANALYSIS", "WF_CUSTOMER_VALIDATION", "WF_BUSINESS_PLAN", "WF_MENU_CARD", "WF_SUPPLIER_LIST", "WF_REAL_ESTATE", "WF_GO_TO_MARKET", "WF_INVENTORY_LAUNCH", "WF_FINANCIAL_PLANNING", "WF_STARTUP_CONSULTING", "WF_DIAGNOSTIC", "WF_NEXT_BEST_ACTIONS", "WF_MARKETING_STRATEGY", "WF_STRATEGIC_PLANNING", "WF_TECH_DIGITALIZATION", "WF_AUTOMATION_ROI", "WF_PHYSICAL_AUTOMATION", "WF_APP_DEVELOPMENT"],
  intake: ["WF_BASELINE", "WF_MARKET", "WF_RESEARCH", "WF_VALUE_PROPOSITION", "WF_BUSINESS_PLAN", "WF_MENU_CARD", "WF_SUPPLIER_LIST", "WF_REAL_ESTATE", "WF_GO_TO_MARKET", "WF_CUSTOMER_VALIDATION", "WF_STRATEGIC_PLANNING"],
  market: ["WF_RESEARCH", "WF_KPI_ESTIMATION", "WF_VALUE_PROPOSITION", "WF_COMPETITOR_ANALYSIS", "WF_SWOT", "WF_TREND_ANALYSIS", "WF_CUSTOMER_VALIDATION", "WF_MENU_CARD", "WF_SUPPLIER_LIST", "WF_REAL_ESTATE", "WF_GO_TO_MARKET", "WF_BUSINESS_PLAN", "WF_STRATEGIC_PLANNING"],
  baseline: ["WF_DIAGNOSTIC", "WF_NEXT_BEST_ACTIONS", "WF_KPI_ESTIMATION", "WF_BUSINESS_PLAN", "WF_RESEARCH", "WF_SUPPLIER_LIST", "WF_REAL_ESTATE", "WF_CUSTOMER_VALIDATION", "WF_VALUE_PROPOSITION", "WF_GO_TO_MARKET", "WF_SWOT", "WF_COMPETITOR_ANALYSIS", "WF_STRATEGIC_PLANNING", "WF_TREND_ANALYSIS"],
  kpi_set: ["WF_NEXT_BEST_ACTIONS", "WF_BASELINE"],
  failure_analysis: ["WF_BUSINESS_PLAN", "WF_NEXT_BEST_ACTIONS"],
  menu_card: ["WF_SUPPLIER_LIST", "WF_MENU_COST"],
  supplier_list: ["WF_BUSINESS_PLAN", "WF_MENU_COST"],
  real_estate: ["WF_BUSINESS_PLAN"],
  industry_research: ["WF_MARKET", "WF_RESEARCH", "WF_KPI_ESTIMATION", "WF_BUSINESS_PLAN"],
  market_research: ["WF_NEXT_BEST_ACTIONS", "WF_MARKETING_STRATEGY", "WF_KPI_ESTIMATION", "WF_BUSINESS_PLAN"],
  best_practices: ["WF_BUSINESS_PLAN", "WF_RESEARCH"],
  swot_analysis: ["WF_BUSINESS_PLAN", "WF_STRATEGIC_PLANNING"],
  competitor_analysis: ["WF_BUSINESS_PLAN", "WF_STRATEGIC_PLANNING"],
  trend_analysis: ["WF_BUSINESS_PLAN", "WF_STRATEGIC_PLANNING"],
  pestel_analysis: ["WF_STRATEGIC_PLANNING", "WF_TREND_ANALYSIS"],
  value_proposition: ["WF_GO_TO_MARKET", "WF_BUSINESS_PLAN"],
  customer_validation: ["WF_BUSINESS_PLAN", "WF_GO_TO_MARKET"],
  diagnostic: ["WF_NEXT_BEST_ACTIONS"],
  business_plan: [],
  go_to_market: ["WF_GROWTH_MARGIN_OPTIMIZATION"],
  financial_planning: ["WF_KPI_ESTIMATION", "WF_GROWTH_MARGIN_OPTIMIZATION"],
  personnel_plan: ["WF_FINANCIAL_PLANNING", "WF_GROWTH_MARGIN_OPTIMIZATION"],
  startup_guide: [],
  scaling_strategy: [],
  customer_economics_ltv_cac: ["WF_SCALING_STRATEGY", "WF_GROWTH_MARGIN_OPTIMIZATION"],
  pmf_assessment: ["WF_SCALING_STRATEGY", "WF_GROWTH_MARGIN_OPTIMIZATION"],
  growth_loops: ["WF_SCALING_STRATEGY", "WF_GROWTH_MARGIN_OPTIMIZATION"],
  growth_margin_optimization: [],
  marketing_strategy: ["WF_GROWTH_MARGIN_OPTIMIZATION"],
  social_media_content_plan: ["WF_MARKETING_STRATEGY", "WF_GROWTH_MARGIN_OPTIMIZATION"],
  conversion_funnel_analysis: ["WF_MARKETING_STRATEGY", "WF_SCALING_STRATEGY", "WF_GROWTH_MARGIN_OPTIMIZATION"],
  hr_planning: [],
  process_optimization: [],
  customer_experience_cx: ["WF_PROCESS_OPTIMIZATION"],
  organization_roles: ["WF_PROCESS_OPTIMIZATION", "WF_FINANCIAL_PLANNING"],
  hiring_talent_strategy: ["WF_PROCESS_OPTIMIZATION", "WF_STARTUP_CONSULTING"],
  portfolio_management: [],
  strategic_options: [],
  data_collection_plan: ["WF_BASELINE"],
  data_strategy: ["WF_DATA_COLLECTION_PLAN", "WF_STRATEGIC_PLANNING"],
  scenario_analysis: ["WF_STRATEGIC_PLANNING"],
  operative_plan: [],
  strategic_planning: [],
  barriers_to_entry: ["WF_STRATEGIC_PLANNING"],
  moat_assessment: ["WF_STRATEGIC_PLANNING"],
  capital_strategy: ["WF_STARTUP_CONSULTING", "WF_FINANCIAL_PLANNING"],
  business_model_mechanics: ["WF_FINANCIAL_PLANNING", "WF_GO_TO_MARKET"],
  tech_digitalization: [],
  automation_roi: [],
  physical_automation: [],
  inventory_equipment_plan: ["WF_FINANCIAL_PLANNING"],
  app_project_plan: ["WF_APP_DEVELOPMENT"],
  app_requirements: ["WF_APP_DEVELOPMENT"],
  app_tech_spec: ["WF_APP_DEVELOPMENT"],
  app_mvp_guide: ["WF_APP_DEVELOPMENT"],
  app_page_specs: ["WF_APP_DEVELOPMENT"],
  app_db_schema: ["WF_APP_DEVELOPMENT"],
};

/** Artifact types produced by each workflow */
export const WORKFLOW_TO_ARTIFACTS: Record<string, string[]> = {
  WF_BUSINESS_FORM: [],
  WF_BASELINE: ["industry_research"],
  WF_MARKET: ["market"],
  WF_RESEARCH: ["market_research", "best_practices", "failure_analysis"],
  WF_VALUE_PROPOSITION: ["value_proposition"],
  WF_COMPETITOR_ANALYSIS: ["competitor_analysis"],
  WF_SWOT: ["swot_analysis"],
  WF_TREND_ANALYSIS: ["trend_analysis", "pestel_analysis"],
  WF_IDEA_USP_VALIDATION: ["value_proposition"],
  WF_FEASIBILITY_VALIDATION: ["scenario_analysis"],
  WF_PATENT_CHECK: ["strategic_options"],
  WF_LEGAL_FOUNDATION: ["startup_guide"],
  WF_CUSTOMER_VALIDATION: ["customer_validation"],
  WF_BUSINESS_PLAN: ["business_plan"],
  WF_MENU_CARD: ["menu_card"],
  WF_SUPPLIER_LIST: ["supplier_list"],
  WF_MENU_COST: ["menu_cost"],
  WF_MENU_PRICING: ["menu_card", "supplier_list", "menu_cost", "menu_preiskalkulation"],
  WF_REAL_ESTATE: ["real_estate"],
  WF_STARTUP_CONSULTING: ["startup_guide", "capital_strategy"],
  WF_GO_TO_MARKET: ["go_to_market"],
  WF_WORK_PROCESSES: ["work_processes"],
  WF_FINANCIAL_PLANNING: ["work_processes", "personnel_plan", "business_model_mechanics", "financial_planning"],
  WF_DIAGNOSTIC: ["diagnostic"],
  WF_NEXT_BEST_ACTIONS: ["decision_pack"],
  WF_MARKETING_STRATEGY: ["marketing_strategy", "conversion_funnel_analysis", "social_media_content_plan"],
  WF_SCALING_STRATEGY: ["scaling_strategy", "customer_economics_ltv_cac", "pmf_assessment", "growth_loops"],
  WF_GROWTH_MARGIN_OPTIMIZATION: ["growth_margin_optimization"],
  WF_PROCESS_OPTIMIZATION: ["process_optimization", "customer_experience_cx", "organization_roles", "hiring_talent_strategy"],
  WF_PORTFOLIO_MANAGEMENT: ["portfolio_management"],
  WF_STRATEGIC_OPTIONS: ["strategic_options"],
  WF_KPI_ESTIMATION: ["kpi_estimation"],
  WF_DATA_COLLECTION_PLAN: ["data_collection_plan", "data_strategy"],
  WF_SCENARIO_ANALYSIS: ["scenario_analysis"],
  WF_OPERATIVE_PLAN: ["operative_plan"],
  WF_STRATEGIC_PLANNING: ["strategic_planning", "barriers_to_entry", "moat_assessment"],
  WF_TECH_DIGITALIZATION: ["tech_digitalization"],
  WF_AUTOMATION_ROI: ["automation_roi"],
  WF_PHYSICAL_AUTOMATION: ["physical_automation"],
  WF_INVENTORY_LAUNCH: ["inventory_equipment_plan"],
  WF_APP_DEVELOPMENT: ["app_project_plan", "app_requirements", "app_tech_spec", "app_mvp_guide", "app_page_specs", "app_db_schema"],
};

/** Category: "analysis" = research/reports (market research, SWOT, …), "artifact" = plans/documents (business plan, …) */
export const ARTIFACT_CATEGORY: Record<string, "analysis" | "artifact"> = {
  baseline: "analysis",
  industry_research: "analysis",
  market: "analysis",
  market_research: "analysis",
  best_practices: "analysis",
  failure_analysis: "analysis",
  diagnostic: "analysis",
  customer_validation: "analysis",
  swot_analysis: "analysis",
  trend_analysis: "analysis",
  pestel_analysis: "analysis",
  competitor_analysis: "analysis",
  knowledge_digest: "analysis",
  strategy_pack: "analysis",
  value_proposition: "artifact",
  business_plan: "artifact",
  supplier_list: "artifact",
  menu_card: "artifact",
  menu_cost: "artifact",
  menu_preiskalkulation: "artifact",
  real_estate: "artifact",
  startup_guide: "artifact",
  go_to_market: "artifact",
  work_processes: "artifact",
  financial_planning: "artifact",
  personnel_plan: "artifact",
  scaling_strategy: "artifact",
  customer_economics_ltv_cac: "analysis",
  pmf_assessment: "analysis",
  growth_loops: "artifact",
  growth_margin_optimization: "artifact",
  marketing_strategy: "artifact",
  social_media_content_plan: "artifact",
  conversion_funnel_analysis: "analysis",
  hr_planning: "artifact",
  process_optimization: "artifact",
  customer_experience_cx: "artifact",
  organization_roles: "artifact",
  hiring_talent_strategy: "artifact",
  portfolio_management: "artifact",
  strategic_options: "artifact",
  kpi_estimation: "analysis",
  data_collection_plan: "artifact",
  data_strategy: "artifact",
  scenario_analysis: "artifact",
  operative_plan: "artifact",
  strategic_planning: "artifact",
  barriers_to_entry: "analysis",
  moat_assessment: "analysis",
  capital_strategy: "artifact",
  business_model_mechanics: "artifact",
  decision_pack: "artifact",
  tech_digitalization: "artifact",
  automation_roi: "artifact",
  physical_automation: "artifact",
  inventory_equipment_plan: "artifact",
  app_project_plan: "artifact",
  app_requirements: "artifact",
  app_tech_spec: "artifact",
  app_mvp_guide: "artifact",
  app_page_specs: "artifact",
  app_db_schema: "artifact",
};

/** Human-readable labels for artifact types */
export const ARTIFACT_LABELS: Record<string, string> = {
  baseline: "KPI Gap Report",
  industry_research: "Branchenanalyse",
  market: "Marktüberblick",
  market_research: "Marktanalyse",
  best_practices: "Best Practices",
  failure_analysis: "Warum Unternehmen scheitern",
  value_proposition: "Wertversprechen",
  competitor_analysis: "Wettbewerbsanalyse",
  swot_analysis: "SWOT-Analyse",
  trend_analysis: "Trendanalyse",
  pestel_analysis: "PESTEL-Analyse",
  customer_validation: "Kundenvalidierung",
  business_plan: "Businessplan",
  menu_card: "Angebotskatalog",
  supplier_list: "Lieferantenliste",
  menu_cost: "Warenkosten",
  menu_preiskalkulation: "Preiskalkulation",
  real_estate: "Standortoptionen",
  startup_guide: "Förderung",
  go_to_market: "Go-to-Market & Pricing",
  work_processes: "Arbeitsprozesse",
  personnel_plan: "Personalplan & Personalkosten",
  financial_planning: "Finanzplanung",
  diagnostic: "Ursachenanalyse",
  decision_pack: "Top-Entscheidungen",
  scaling_strategy: "Skalierungsstrategie",
  customer_economics_ltv_cac: "Customer Economics (LTV/CAC)",
  pmf_assessment: "Product-Market-Fit Assessment",
  growth_loops: "Growth Loops",
  growth_margin_optimization: "Marge, Angebot & Kostenoptimierung",
  marketing_strategy: "Marketing Strategie",
  social_media_content_plan: "Social Media Content Plan",
  conversion_funnel_analysis: "Conversion Funnel Analyse",
  hr_planning: "Personalplanung",
  process_optimization: "Prozessoptimierung",
  customer_experience_cx: "Customer Experience (CX)",
  organization_roles: "Organisation & Rollen",
  hiring_talent_strategy: "Hiring & Talent Strategie",
  portfolio_management: "Portfolio- & Markenstrategie",
  strategic_options: "Strategische Optionen",
  kpi_estimation: "KPI-Schätzung",
  data_collection_plan: "Datenerhebungsplan",
  data_strategy: "Data Strategy",
  scenario_analysis: "Szenario- & Risikoanalyse",
  operative_plan: "Operativer Plan",
  strategic_planning: "Strategische Planung",
  barriers_to_entry: "Barriers to Entry",
  moat_assessment: "Moat Assessment",
  capital_strategy: "Capital Strategy",
  business_model_mechanics: "Business Model Mechanics",
  tech_digitalization: "Technologie & Digitalisierung",
  automation_roi: "Computer-Automatisierung & ROI",
  physical_automation: "Physische Automatisierung",
  inventory_equipment_plan: "Inventar & Equipment (Launch)",
  app_project_plan: "App-Projektplan",
  app_requirements: "App-Requirements",
  app_tech_spec: "App-Technische Spezifikation",
  app_mvp_guide: "App-MVP-Anleitung",
  app_page_specs: "App-Seiten-Spezifikation",
  app_db_schema: "App-Datenbank-Schema",
};

/** Workflow-Namen für UI */
export const WORKFLOW_NAMES: Record<string, string> = {
  WF_BUSINESS_FORM: "Unternehmensformular",
  WF_BASELINE: "Grundlagenanalyse & KPI-Set",
  WF_MARKET: "Marktüberblick",
  WF_RESEARCH: "Marktanalyse",
  WF_VALUE_PROPOSITION: "Wertversprechen",
  WF_COMPETITOR_ANALYSIS: "Wettbewerbsanalyse",
  WF_SWOT: "SWOT",
  WF_TREND_ANALYSIS: "Trendanalyse",
  WF_IDEA_USP_VALIDATION: "Idee- & USP-Validierung",
  WF_FEASIBILITY_VALIDATION: "Umsetzbarkeitsvalidierung",
  WF_PATENT_CHECK: "Patentrecht & Schutzfähigkeit",
  WF_LEGAL_FOUNDATION: "Rechtliche Vorgaben & Unternehmensform",
  WF_CUSTOMER_VALIDATION: "Kundenvalidierung",
  WF_MENU_CARD: "Angebotskatalog",
  WF_SUPPLIER_LIST: "Lieferantenliste",
  WF_MENU_COST: "Warenkosten",
  WF_MENU_PRICING: "Menü & Preiskalkulation",
  WF_REAL_ESTATE: "Standortoptionen",
  WF_BUSINESS_PLAN: "Businessplan",
  WF_STARTUP_CONSULTING: "Förderung",
  WF_GO_TO_MARKET: "Go-to-Market",
  WF_FINANCIAL_PLANNING: "Finanzplanung",
  WF_DIAGNOSTIC: "Root Cause Analysis",
  WF_NEXT_BEST_ACTIONS: "Top Decisions",
  WF_MARKETING_STRATEGY: "Marketing Strategie",
  WF_SCALING_STRATEGY: "Skalierungsstrategie",
  WF_GROWTH_MARGIN_OPTIMIZATION: "Marge, Angebot & Kostenoptimierung",
  WF_PROCESS_OPTIMIZATION: "Prozessoptimierung",
  WF_PORTFOLIO_MANAGEMENT: "Portfoliomanagement",
  WF_STRATEGIC_OPTIONS: "Strategische Optionen",
  WF_KPI_ESTIMATION: "KPI-Schätzung",
  WF_DATA_COLLECTION_PLAN: "Datenerhebungsplan",
  WF_STRATEGIC_PLANNING: "Strategische Planung",
  WF_SCENARIO_ANALYSIS: "Szenarioanalyse",
  WF_OPERATIVE_PLAN: "Operativer Plan",
  WF_TECH_DIGITALIZATION: "Technologie & Digitalisierung",
  WF_AUTOMATION_ROI: "Computer-Automatisierung & ROI",
  WF_PHYSICAL_AUTOMATION: "Physische Prozess-Automatisierung",
  WF_INVENTORY_LAUNCH: "Inventar & Equipment (Markteintritt)",
  WF_APP_DEVELOPMENT: "Eigene App – Entwicklung",
};

/** Englische Kurznamen für Study-UI und locale=en (Keys identisch zu {@link WORKFLOW_NAMES}). */
export const WORKFLOW_NAMES_EN: Record<string, string> = {
  WF_BUSINESS_FORM: "Business form",
  WF_BASELINE: "Baseline analysis & KPI set",
  WF_MARKET: "Market overview",
  WF_RESEARCH: "Market research",
  WF_VALUE_PROPOSITION: "Value proposition",
  WF_COMPETITOR_ANALYSIS: "Competitor analysis",
  WF_SWOT: "SWOT",
  WF_TREND_ANALYSIS: "Trend analysis",
  WF_IDEA_USP_VALIDATION: "Idea & USP validation",
  WF_FEASIBILITY_VALIDATION: "Feasibility validation",
  WF_PATENT_CHECK: "Patents & protectability",
  WF_LEGAL_FOUNDATION: "Legal requirements & business form",
  WF_CUSTOMER_VALIDATION: "Customer validation",
  WF_MENU_CARD: "Offer catalog",
  WF_SUPPLIER_LIST: "Supplier list",
  WF_MENU_COST: "Cost of goods",
  WF_MENU_PRICING: "Menu & pricing",
  WF_REAL_ESTATE: "Location options",
  WF_BUSINESS_PLAN: "Business plan",
  WF_STARTUP_CONSULTING: "Funding / grants",
  WF_GO_TO_MARKET: "Go-to-market",
  WF_FINANCIAL_PLANNING: "Financial planning",
  WF_DIAGNOSTIC: "Root cause analysis",
  WF_NEXT_BEST_ACTIONS: "Top decisions",
  WF_MARKETING_STRATEGY: "Marketing strategy",
  WF_SCALING_STRATEGY: "Scaling strategy",
  WF_GROWTH_MARGIN_OPTIMIZATION: "Margin, offering & cost optimization",
  WF_PROCESS_OPTIMIZATION: "Process optimization",
  WF_PORTFOLIO_MANAGEMENT: "Portfolio management",
  WF_STRATEGIC_OPTIONS: "Strategic options",
  WF_KPI_ESTIMATION: "KPI estimation",
  WF_DATA_COLLECTION_PLAN: "Data collection plan",
  WF_STRATEGIC_PLANNING: "Strategic planning",
  WF_SCENARIO_ANALYSIS: "Scenario analysis",
  WF_OPERATIVE_PLAN: "Operational plan",
  WF_TECH_DIGITALIZATION: "Technology & digitalization",
  WF_AUTOMATION_ROI: "Computer automation & ROI",
  WF_PHYSICAL_AUTOMATION: "Physical process automation",
  WF_INVENTORY_LAUNCH: "Inventory & equipment (market entry)",
  WF_APP_DEVELOPMENT: "Custom app development",
};

export function workflowDisplayName(locale: Locale, workflowKey: string): string {
  if (locale === "de") {
    return WORKFLOW_NAMES[workflowKey] ?? workflowKey;
  }
  return WORKFLOW_NAMES_EN[workflowKey] ?? WORKFLOW_NAMES[workflowKey] ?? workflowKey;
}

/** Unterworkflows (Steps) pro Workflow – für Anzeige */
export const WORKFLOW_STEP_LABELS: Record<string, string[]> = {
  WF_BUSINESS_FORM: ["Unternehmensformular"],
  WF_BASELINE: ["Geschäftsmodell", "KPI-Set", "Branchenanalyse"],
  WF_MARKET: ["Marktüberblick"],
  WF_RESEARCH: ["Marktanalyse", "Best Practices", "Warum Unternehmen scheitern"],
  WF_MENU_CARD: ["Angebotskatalog (Intro + Vollständig)"],
  WF_SUPPLIER_LIST: ["Lieferantenliste"],
  WF_MENU_COST: ["Warenkosten"],
  WF_MENU_PRICING: ["Menü", "Lieferanten", "Warenkosten", "Preiskalkulation"],
  WF_REAL_ESTATE: ["Standortoptionen"],
  WF_DIAGNOSTIC: ["Ursachenbäume"],
  WF_NEXT_BEST_ACTIONS: ["Entscheidungslogik"],
  WF_BUSINESS_PLAN: ["Executive Summary", "Marktanalyse", "Marketingstrategie", "Finanzszenarien", "Risikoanalyse"],
  WF_KPI_ESTIMATION: ["KPI-Schätzung"],
  WF_DATA_COLLECTION_PLAN: ["Datenerhebungsplan", "Data Strategy"],
  WF_STARTUP_CONSULTING: ["Funding", "Capital Strategy"],
  WF_CUSTOMER_VALIDATION: ["MVP", "Kundeninterviews", "Landingpage-Tests", "Pilotkunden", "Prototypen"],
  WF_STRATEGIC_OPTIONS: ["neue Geschäftsmodelle", "neue Märkte", "M&A", "Börsengang", "Nachfolgeplanung"],
  WF_VALUE_PROPOSITION: ["Wertversprechen & Problem-Lösungs-Fit"],
  WF_GO_TO_MARKET: ["Go-to-Market & Pricing"],
  WF_MARKETING_STRATEGY: ["Marketing Strategie", "Conversion Funnel Analyse", "Social Media Content Plan"],
  WF_SCALING_STRATEGY: ["Skalierbarkeit", "Automatisierung", "Marketing-Skalierung", "Vertriebssysteme", "Customer Economics (LTV/CAC)", "PMF Assessment", "Growth Loops"],
  WF_GROWTH_MARGIN_OPTIMIZATION: ["Deckungsbeitrag & Marge", "Angebots- & Packaging-Logik", "Marketing- & ROI-Hebel", "Kosten, Personal, Einkauf & Energie"],
  WF_PROCESS_OPTIMIZATION: ["Prozessoptimierung", "Kostenmanagement", "Markenstrategie", "Internationalisierung", "Customer Experience (CX)", "Organisation & Rollen", "Hiring & Talent Strategie"],
  WF_PORTFOLIO_MANAGEMENT: ["Produktportfolio optimieren", "Marktsegmente erweitern", "strategische Partnerschaften"],
  WF_SCENARIO_ANALYSIS: ["Szenario- & Risikoanalyse"],
  WF_OPERATIVE_PLAN: ["Operativer Plan"],
  WF_COMPETITOR_ANALYSIS: ["Wettbewerbsanalyse"],
  WF_SWOT: ["SWOT-Analyse"],
  WF_FINANCIAL_PLANNING: ["Arbeitsprozesse (Planung → Endkunde)", "Personalplan & Personalkosten", "Business Model Mechanics", "Liquiditätsplan", "Rentabilitätsplan", "Kapitalbedarf", "Break-Even"],
  WF_IDEA_USP_VALIDATION: ["Idee- und USP-Check"],
  WF_FEASIBILITY_VALIDATION: ["Machbarkeit & Voraussetzungen"],
  WF_PATENT_CHECK: ["Patentierbarkeit & Quellenprüfung"],
  WF_LEGAL_FOUNDATION: ["Rechtsrahmen & Unternehmensform"],
  WF_STRATEGIC_PLANNING: ["Strategische Planung", "Barriers to Entry", "Moat Assessment"],
  WF_TREND_ANALYSIS: ["Trendanalyse", "PESTEL-Analyse"],
  WF_TECH_DIGITALIZATION: ["Kassensystem", "Dokumentenarchivierung", "Buchhaltung", "CRM", "Weitere Tools"],
  WF_AUTOMATION_ROI: ["Automatisierbare Prozesse", "Kosten & ROI"],
  WF_PHYSICAL_AUTOMATION: ["Teigmaschine", "Thermomix", "Laufbänder", "Kosten & ROI"],
  WF_INVENTORY_LAUNCH: ["Inventar & Rechtsform", "Prozesse & Bestand", "Markteintritt: fehlende Anschaffungen", "Effizienz & Skalierung"],
  WF_APP_DEVELOPMENT: ["Ideen", "Projektplan", "Requirements", "Tech-Spec", "MVP-Anleitung", "Seiten-Spec", "DB-Schema"],
};

export type PlanningPhase = {
  id: string;
  name: string;
  goal: string;
  workflowKeys: string[];
  instruments?: string[];
  criticalFactors?: string[];
  typicalMistakes?: string[];
  financialPlanningIncludes?: string[];
  strategicQuestions?: string[];
  keyMeasures?: string[];
  planningFocus?: string[];
};

export type PlanningArea = {
  id: string;
  name: string;
  description: string;
  horizon?: string;
  examples?: string[];
  instruments?: string[];
  workflowKeys: string[];
};

/** 6 Planungsphasen (zeitlich) */
export const PLANNING_PHASES: PlanningPhase[] = [
  {
    id: "ideation",
    name: "Ideations- / Konzeptphase",
    goal: "Prüfen, ob eine Geschäftsidee grundsätzlich tragfähig ist.",
    workflowKeys: ["WF_BUSINESS_FORM", "WF_BASELINE", "WF_MARKET", "WF_RESEARCH", "WF_VALUE_PROPOSITION", "WF_COMPETITOR_ANALYSIS", "WF_SWOT", "WF_TREND_ANALYSIS"],
    instruments: ["Problem-Solution-Fit", "Marktanalyse", "Trendanalyse", "Wettbewerbsanalyse", "SWOT-Analyse", "Zielgruppenanalyse", "Value Proposition Design"],
    criticalFactors: ["Realer Kundenbedarf", "Klar definierter Zielmarkt", "Differenzierung vom Wettbewerb"],
    typicalMistakes: ["Produkt entwickeln ohne Marktbedarf", "Zielgruppe zu breit definieren", "Konkurrenz ignorieren"],
  },
  {
    id: "validation",
    name: "Validierungsphase",
    goal: "Beweisen, dass Kunden tatsächlich kaufen würden.",
    workflowKeys: [
      "WF_IDEA_USP_VALIDATION",
      "WF_FEASIBILITY_VALIDATION",
      "WF_PATENT_CHECK",
      "WF_LEGAL_FOUNDATION",
      "WF_CUSTOMER_VALIDATION",
    ],
    instruments: ["Problem-Solution-Fit", "USP-Check", "Machbarkeitsprüfung", "Patentrecherche", "Recht/Unternehmensform", "MVP", "Kundeninterviews", "Landingpage-Tests", "Pilotkunden", "Prototypen"],
    criticalFactors: ["Schnelle Tests statt Perfektion", "Hypothesen testen", "Kundenfeedback priorisieren"],
    typicalMistakes: ["Zu viel Entwicklung vor Markttest", "Freunde statt echte Zielkunden fragen"],
  },
  {
    id: "launch",
    name: "Gründungs- / Launchphase",
    goal: "Unternehmen offiziell starten und erste Umsätze generieren.",
    workflowKeys: ["WF_MENU_PRICING", "WF_REAL_ESTATE", "WF_STARTUP_CONSULTING", "WF_GO_TO_MARKET", "WF_INVENTORY_LAUNCH", "WF_FINANCIAL_PLANNING", "WF_BUSINESS_PLAN", "WF_KPI_ESTIMATION"],
    instruments: ["Businessplan", "Finanzplanung", "Rechtsform", "Pricing Strategie", "Go-to-Market Strategie", "Marketingstrategie", "Vertriebskanäle"],
    criticalFactors: ["Cashflow Management", "Kundengewinnungskosten", "Vertriebssystem"],
    typicalMistakes: ["Marketingbudget unterschätzen", "falsche Preisstrategie", "keine Liquiditätsreserve"],
    financialPlanningIncludes: ["Liquiditätsplan", "Rentabilitätsplan", "Kapitalbedarf", "Break-Even Analyse"],
  },
  {
    id: "scaling",
    name: "Wachstumsphase",
    goal: "Umsatz steigern und Marktanteile gewinnen.",
    workflowKeys: ["WF_DIAGNOSTIC", "WF_NEXT_BEST_ACTIONS", "WF_MARKETING_STRATEGY", "WF_SCALING_STRATEGY", "WF_GROWTH_MARGIN_OPTIMIZATION"],
    instruments: ["Skalierung des Geschäftsmodells", "Automatisierung", "Teamaufbau", "Marketing-Skalierung", "Vertriebssysteme"],
    criticalFactors: ["CAC", "LTV", "Conversion Rate", "Churn Rate", "Umsatzwachstum"],
    typicalMistakes: ["zu frühes Hiring", "Skalieren ohne funktionierenden Vertrieb", "Prozesse nicht standardisiert"],
    strategicQuestions: ["Wie skalierbar ist das Modell?", "Welche Prozesse müssen automatisiert werden?", "Welche Märkte können erschlossen werden?"],
  },
  {
    id: "tech_digital",
    name: "Technologie & Digitalisierung",
    goal: "Passende Technologie-Tools und Automatisierung identifizieren.",
    workflowKeys: ["WF_TECH_DIGITALIZATION", "WF_AUTOMATION_ROI", "WF_PHYSICAL_AUTOMATION", "WF_APP_DEVELOPMENT"],
    instruments: ["Kassensystem", "Dokumentenarchivierung", "Buchhaltung", "RPA", "Physische Automatisierung", "Eigene App"],
    criticalFactors: ["ROI", "Skalierbarkeit", "Kosten-Nutzen"],
    typicalMistakes: ["Überinvestition in Technologie", "Automatisierung ohne Prozessoptimierung"],
  },
  {
    id: "maturity",
    name: "Reifephase",
    goal: "Profitabilität und Effizienz maximieren.",
    workflowKeys: ["WF_PROCESS_OPTIMIZATION", "WF_PORTFOLIO_MANAGEMENT"],
    instruments: ["Prozessoptimierung", "Kostenmanagement", "Portfolio Management", "Markenstrategie", "Internationalisierung"],
    criticalFactors: ["EBITDA", "Gewinnmarge", "Marktanteil", "Kundenbindung"],
    typicalMistakes: ["Innovation stoppen", "zu starke Bürokratie", "neue Wettbewerber unterschätzen"],
    keyMeasures: ["Produktportfolio optimieren", "Marktsegmente erweitern", "strategische Partnerschaften"],
  },
  {
    id: "renewal",
    name: "Erneuerung / Exit / Transformation",
    goal: "Unternehmen neu ausrichten oder verkaufen.",
    workflowKeys: ["WF_STRATEGIC_OPTIONS"],
    instruments: ["neue Geschäftsmodelle", "neue Märkte", "M&A", "Börsengang", "Nachfolgeplanung"],
    criticalFactors: ["Unternehmensbewertung", "Wachstumspotenzial", "strategischer Fit"],
    typicalMistakes: [],
    planningFocus: ["Innovationsstrategie", "Portfolioanpassung", "Unternehmenswert steigern"],
  },
];

/** Reihenfolge wie auf der Pläne-Seite (Dashboard): PLANNING_PHASES nacheinander, dann Querschnittsbereiche */
const PHASES_ORDER = PLANNING_PHASES.flatMap((p) => p.workflowKeys);
const CROSS_CUTTING = ["WF_DATA_COLLECTION_PLAN", "WF_STRATEGIC_PLANNING", "WF_SCENARIO_ANALYSIS", "WF_OPERATIVE_PLAN"];
export const WIZARD_WORKFLOW_ORDER: string[] = [
  ...PHASES_ORDER,
  ...CROSS_CUTTING.filter((k) => !PHASES_ORDER.includes(k)),
];

/** 5 Planungsbereiche (parallel zu allen Phasen) */
export const PLANNING_AREAS: PlanningArea[] = [
  {
    id: "strategic",
    name: "Strategische Planung",
    description: "Langfristige Unternehmensausrichtung",
    horizon: "3–10 Jahre",
    examples: ["Marktposition", "Wettbewerbsvorteile", "Innovation"],
    workflowKeys: ["WF_NEXT_BEST_ACTIONS", "WF_VALUE_PROPOSITION", "WF_STRATEGIC_PLANNING", "WF_COMPETITOR_ANALYSIS", "WF_STRATEGIC_OPTIONS"],
  },
  {
    id: "operative",
    name: "Operative Planung",
    description: "Konkrete Umsetzung der Strategie",
    examples: ["Jahresplanung", "Marketingplan", "Vertriebsplanung", "Budgetplanung"],
    workflowKeys: ["WF_DATA_COLLECTION_PLAN", "WF_OPERATIVE_PLAN"],
  },
  {
    id: "financial",
    name: "Finanzplanung",
    description: "Sichert Liquidität und Wachstum",
    instruments: ["Liquiditätsplanung", "Budgetplanung", "Investitionsplanung", "Break-Even Analyse"],
    examples: ["Liquiditätsplanung", "Budgetplanung", "Investitionsplanung", "Break-Even Analyse"],
    workflowKeys: ["WF_BUSINESS_PLAN", "WF_MENU_PRICING", "WF_REAL_ESTATE", "WF_FINANCIAL_PLANNING"],
  },
  {
    id: "hr",
    name: "Personalplanung",
    description: "Aufbau und Entwicklung von Teams",
    examples: ["Hiring-Plan", "Organisationsstruktur", "Kompetenzaufbau"],
    workflowKeys: [],
  },
  {
    id: "risk",
    name: "Risiko- und Szenarioplanung",
    description: "Vorbereitung auf Unsicherheit",
    instruments: ["Szenarioanalyse", "Sensitivitätsanalyse", "Risikomatrix"],
    examples: ["Szenarioanalyse", "Sensitivitätsanalyse", "Risikomatrix"],
    workflowKeys: ["WF_RESEARCH", "WF_SCENARIO_ANALYSIS"],
  },
];
